preset: laravel

disabled:
    #  - self_accessor

enabled:
  - mb_str_functions
  - no_homoglyph_names
  - non_printable_character
  - random_api_migration
  - final_internal_class
  - void_return
  - strict_comparison
  - ereg_to_preg

finder:
#  include:
#    - "app"
#    - "src"
  not-name:
    - "*.php.twig"
  not-path:
    - "src/StyleCI/Fixers.php"
  exclude:
    - "vendors"
    - "storage"
    - "node_modules"